project:
  type: website

website:
  title: "Ana Zysko"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: CV.pdf
        text: CV
      - href: Assignments.qmd
        text: Assignments
      - href: ProjectProposal.pdf
        text: Project Proposal
      - href: FinalProject.pdf
        text: Final Project
      - href: https://azysko.github.io/Blog/
        text: Blog


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

